ARG ALPINE_VERSION=3.23

FROM alpine:${ALPINE_VERSION} AS nginx-builder

ENV NGINX_VERSION=1.27.1
ENV NGX_BROTLI_COMMIT=f2e20e6a94a2267d0cdff8073060e3356ebf9d9c
ENV NGINX_CONFIG="\
        --prefix=/etc/nginx \
        --sbin-path=/usr/sbin/nginx \
        --modules-path=/usr/lib/nginx/modules \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --pid-path=/var/run/nginx.pid \
        --lock-path=/var/run/nginx.lock \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --user=nginx \
        --group=nginx \
        --with-http_gzip_static_module \
        --with-threads \
        --with-stream \
        --with-compat \
        --with-http_v2_module \
        --add-module=/usr/src/ngx_brotli \
    "

RUN apk add --no-cache \
        gcc libc-dev make pcre-dev zlib-dev brotli-dev linux-headers \
        curl gnupg tar autoconf libtool automake git g++ cmake gettext

COPY gpg/ /tmp/gpg

RUN mkdir -p /usr/src/ngx_brotli \
    && cd /usr/src/ngx_brotli \
    && git init \
    && git remote add origin https://github.com/heymdall-legal/ngx-brotli-cdt.git \
    && git fetch --depth 1 origin "$NGX_BROTLI_COMMIT" \
    && git checkout --recurse-submodules -q FETCH_HEAD \
    && git submodule update --init --depth 1 \
    && cd /usr/src \
    && curl -fSL "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz" -o nginx.tar.gz \
    && curl -fSL "https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz.asc" -o nginx.tar.gz.asc \
    && GNUPGHOME="$(mktemp -d)" \
    && export GNUPGHOME \
    && gpg --import /tmp/gpg/* \
    && gpg --batch --verify nginx.tar.gz.asc nginx.tar.gz \
    && tar -zxC /usr/src -f nginx.tar.gz \
    && cd "/usr/src/nginx-${NGINX_VERSION}" \
    && export CFLAGS="${CFLAGS:-} -Wno-unterminated-string-initialization" \
    && ./configure $NGINX_CONFIG \
    && make -j"$(getconf _NPROCESSORS_ONLN)" \
    && make install \
    && rm -rf /etc/nginx/html/ \
    && mkdir -p /etc/nginx/conf.d /usr/share/nginx/html \
    && install -m644 html/index.html /usr/share/nginx/html/ \
    && install -m644 html/50x.html /usr/share/nginx/html/ \
    && strip /usr/sbin/nginx \
    && scanelf --needed --nobanner /usr/sbin/nginx /usr/bin/envsubst \
        | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
        | sort -u \
        | xargs -r apk info --installed \
        | sort -u > /tmp/runDeps.txt

FROM alpine:${ALPINE_VERSION}

COPY --from=nginx-builder /tmp/runDeps.txt /tmp/runDeps.txt
COPY --from=nginx-builder /etc/nginx /etc/nginx
COPY --from=nginx-builder /usr/sbin/nginx /usr/sbin/nginx
COPY --from=nginx-builder /usr/share/nginx/html /usr/share/nginx/html
COPY --from=nginx-builder /usr/bin/envsubst /usr/local/bin/envsubst
COPY nginx.conf /etc/nginx/nginx.conf

RUN addgroup -g 101 -S nginx \
    && adduser --uid 100 -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
    && apk add --no-cache tzdata $(cat /tmp/runDeps.txt) \
    && rm /tmp/runDeps.txt \
    && mkdir -p /var/log/nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443
STOPSIGNAL SIGTERM
